# Generated by Django 2.1.5 on 2019-03-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theaters',
            field=models.ManyToManyField(to='ticketingApps.Theater'),
        ),
        migrations.DeleteModel(
            name='Usertheater',
        ),
    ]
