# Generated by Django 2.1.5 on 2019-03-31 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0004_auto_20190331_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('creditcard', models.ForeignKey(db_column='CreditCard_CreditCardID', on_delete=django.db.models.deletion.DO_NOTHING, to='ticketingApps.Creditcard')),
                ('profile', models.ForeignKey(db_column='Profile_UserID', on_delete=django.db.models.deletion.DO_NOTHING, to='ticketingApps.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='room',
            name='theater_theaterid',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
