# Generated by Django 2.1.5 on 2019-04-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0006_auto_20190331_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='moviecol',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='moviecol1',
        ),
    ]
