# Generated by Django 2.1.5 on 2019-04-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0009_auto_20190331_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
