# Generated by Django 2.1.5 on 2019-04-01 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0010_theater_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatsbought',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 23, 55, 8, 947668, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='seatsbought',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
