# Generated by Django 2.1.5 on 2019-04-02 01:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0011_auto_20190401_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creditcard',
            field=models.ForeignKey(db_column='CreditCard_CreditCardID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketingApps.Creditcard'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(db_column='Profile_UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketingApps.Profile'),
        ),
        migrations.AlterField(
            model_name='seatsbought',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 1, 50, 2, 237693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='theater',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
