# Generated by Django 2.1.5 on 2019-04-02 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0013_auto_20190402_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='order',
            name='qrcodetext',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seatsbought',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 7, 18, 35, 941520, tzinfo=utc)),
        ),
    ]
