# Generated by Django 2.1.5 on 2019-04-02 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0014_auto_20190402_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatsbought',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 15, 16, 30, 343534, tzinfo=utc)),
        ),
    ]
