# Generated by Django 2.1.5 on 2019-04-02 20:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0015_auto_20190402_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshowing',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketingApps.Movie'),
        ),
        migrations.AlterField(
            model_name='movieshowing',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_of', to='ticketingApps.Room'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(db_column='Profile_UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketingApps.Profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketingApps.Theater'),
        ),
        migrations.AlterField(
            model_name='seatsbought',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 21, 6, 3, 644935, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seatsbought',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of', to='ticketingApps.Order'),
        ),
        migrations.AlterField(
            model_name='seatsbought',
            name='showing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showing_of', to='ticketingApps.Movieshowing'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketingApps.Order'),
        ),
    ]
