# Generated by Django 2.1.5 on 2019-04-04 02:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0017_auto_20190403_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieshowing',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketingApps.PricingGroup'),
        ),
        migrations.AlterField(
            model_name='seatsbought',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 2, 22, 4, 547589, tzinfo=utc)),
        ),
    ]
