# Generated by Django 2.1.5 on 2019-04-05 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0018_auto_20190403_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieruntime',
            field=models.PositiveIntegerField(blank=True, db_column='MovieRuntime', null=True),
        ),
        migrations.AlterField(
            model_name='seatsbought',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 4, 58, 15, 775316, tzinfo=utc)),
        ),
    ]
