# Generated by Django 2.1.5 on 2019-04-06 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0019_auto_20190404_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movietitle',
            field=models.CharField(db_column='MovieTitle', default='Titleless', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seatsbought',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 22, 18, 15, 836243, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='theater',
            name='theatername',
            field=models.CharField(db_column='TheaterName', default='Nameless', max_length=45),
            preserve_default=False,
        ),
    ]
