# Generated by Django 2.1.5 on 2019-04-08 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingApps', '0026_auto_20190407_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='price',
        ),
        migrations.AlterField(
            model_name='seatsbought',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 22, 46, 13, 998160, tzinfo=utc)),
        ),
    ]
